# Generated by Django 5.1 on 2025-08-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_achievement_teacher_remove_student_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='board',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('WBBSE', 'WBBSE'), ('WBCHSE', 'WBCHSE'), ('ICSE', 'ICSE'), ('ISC', 'ISC')], max_length=50),
        ),
    ]
