# Generated by Django 5.1 on 2025-08-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the study material', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the material', null=True)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('WBBSE', 'WBBSE'), ('WBCHSE', 'WBCHSE'), ('ICSE', 'ICSE'), ('ISC', 'ISC')], help_text='Educational board', max_length=50)),
                ('class_level', models.IntegerField(choices=[(1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')], help_text='Class level')),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Arts', 'Arts'), ('English', 'English'), ('Hindi', 'Hindi'), ('Bengali', 'Bengali'), ('Social Science', 'Social Science'), ('Physical Science', 'Physical Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Nutrition', 'Nutrition'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Geography', 'Geography'), ('History', 'History'), ('Political Science', 'Political Science'), ('All', 'All Subjects')], help_text='Subject', max_length=100)),
                ('google_drive_link', models.URLField(help_text='Google Drive sharing link', max_length=500)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this material is currently available')),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'ordering': ['board', 'class_level', 'subject', 'title'],
            },
        ),
    ]
