# Generated by Django 5.1 on 2025-08-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_studymaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Arts', 'Arts'), ('English', 'English'), ('Hindi', 'Hindi'), ('Bengali', 'Bengali'), ('Social Science', 'Social Science'), ('Physical Science', 'Physical Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Life Science', 'Life Science'), ('Biology', 'Biology'), ('Nutrition', 'Nutrition'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Geography', 'Geography'), ('History', 'History'), ('Political Science', 'Political Science'), ('All', 'All Subjects')], help_text='Subject', max_length=100),
        ),
    ]
