# Generated by Django 5.1 on 2025-08-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_studymaterial_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='subject',
            field=models.CharField(choices=[('Science', 'Science'), ('English', 'English'), ('Arts', 'Arts'), ('Mathematics', 'Mathematics'), ('Physical Science', 'Physical Science'), ('Life Science', 'Life Science'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Nutrition', 'Nutrition'), ('Bengali', 'Bengali')], help_text='Subject', max_length=100),
        ),
    ]
