# Generated by Django 5.1 on 2025-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_studymaterial_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='class_level',
            field=models.IntegerField(choices=[(5, 'Class 5'), (6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')], help_text='Class level'),
        ),
    ]
