# Generated by Django 5.1 on 2025-08-15 12:05

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_achievement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default=['MON'], max_length=27),
        ),
        migrations.AlterField(
            model_name='payment',
            name='months',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=['1'], max_length=100),
        ),
    ]
