# Generated by Django 5.1 on 2025-08-15 07:16

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_alter_payment_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='months',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=100),
        ),
    ]
