# Generated by Django 5.1 on 2025-08-15 07:16

from django.db import migrations


def convert_months_to_strings(apps, schema_editor):
    """Convert any integer months values to strings"""
    Payment = apps.get_model('myapp', 'Payment')
    
    for payment in Payment.objects.all():
        if payment.months:
            # Convert any integer values to strings
            if isinstance(payment.months, str) and payment.months.strip():
                # Parse the months field if it's stored as a string representation of a list
                try:
                    # Handle case where months might be stored as "[1, 2]" string
                    import ast
                    if payment.months.startswith('[') and payment.months.endswith(']'):
                        month_list = ast.literal_eval(payment.months)
                        payment.months = ','.join(str(m) for m in month_list)
                    # Handle case where months might be stored as "1,2,3"
                    elif ',' in payment.months:
                        month_list = payment.months.split(',')
                        payment.months = ','.join(str(m).strip() for m in month_list)
                    payment.save()
                except:
                    # If parsing fails, set to default
                    payment.months = '1'
                    payment.save()


def reverse_convert_months(apps, schema_editor):
    """Reverse function - not needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_fix_payment_months_default'),
    ]

    operations = [
        migrations.RunPython(convert_months_to_strings, reverse_convert_months),
    ]
